apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor
  labels:
    name: supervisor
spec:
  selector:
    matchLabels:
      name: supervisor
  template:
    metadata:
      labels:
        name: supervisor
    spec:
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          name: supervisor
          image: supervisor-img
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
            - containerPort: 8237
            - containerPort: 8126
            - containerPort: 9003
            - containerPort: 20173
            - containerPort: 20295
            - containerPort: 3933

#          resources:
#            limits:
#              memory: "3072Mi"
#            requests:
#              memory: "3072Mi"
